application: fbalbumshare
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: main.py
  
- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images
  
- url: /album
  script: main.py
  
- url: /terms
  static_files: static/terms.html
  upload: static/(.*)